package i5.las2peer.services.whiteboardPersistenceService;

import java.net.HttpURLConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;

import com.fasterxml.jackson.core.JsonProcessingException;

import i5.las2peer.api.Service;
import i5.las2peer.restMapper.HttpResponse;
import i5.las2peer.restMapper.MediaType;
import i5.las2peer.restMapper.RESTMapper;
import i5.las2peer.restMapper.annotations.ContentParam;
import i5.las2peer.restMapper.annotations.Version;
import i5.las2peer.services.whiteboardPersistenceService.database.DatabaseManager;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import io.swagger.jaxrs.Reader;
import io.swagger.models.Swagger;
import io.swagger.util.Json;


/**
 * 
 * Whiteboard Microservice
 * 
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 * 
 */
@Path("whiteboard")
@Version("0.1") // this annotation is used by the XML mapper
@Api
@SwaggerDefinition(info = @Info(title = "Whiteboard Microservice", version = "0.1",
    description = "A LAS2peer microservice generated by the CAE.", termsOfService = "none",
    contact = @Contact(name = "Peter de Lange", email = "CAEAddress@gmail.com") ,
    license = @License(name = "BSD",
        url = "https://github.com/CAE-Community-Application-Editor/microservice-Whiteboard-Microservice/blob/master/LICENSE.txt") ) )
public class WhiteboardPersistenceService extends Service {


  /*
   * Database configuration
   */
  private String jdbcDriverClassName;
  private String jdbcLogin;
  private String jdbcPass;
  private String jdbcUrl;
  private String jdbcSchema;
  private DatabaseManager dbm;


  public WhiteboardPersistenceService() {
    // read and set properties values
    setFieldValues();
    // instantiate a database manager to handle database connection pooling and credentials
    dbm = new DatabaseManager(jdbcDriverClassName, jdbcLogin, jdbcPass, jdbcUrl, jdbcSchema);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods.
  // //////////////////////////////////////////////////////////////////////////////////////


  /**
   * 
   * storePage
   * 
   * @param whiteboardContent a String
   * 
   * @return HttpResponse
   * 
   */
  @POST
  @Path("/")
  @Produces(MediaType.TEXT_PLAIN)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
      @ApiResponse(code = HttpURLConnection.HTTP_INTERNAL_ERROR, message = "InternalError"),
      @ApiResponse(code = HttpURLConnection.HTTP_CREATED, message = "PageStored")})
  @ApiOperation(value = "storePage", notes = "")
  public HttpResponse storePage(@ContentParam String whiteboardContent) {
    String insertQuery = "";
    Connection conn = null;
    PreparedStatement stmnt = null;
    try {
      conn = dbm.getConnection();
      // formulate statement
      insertQuery = "INSERT INTO page (content) " + "VALUES ('" + whiteboardContent + "');";
      stmnt = conn.prepareStatement(insertQuery);
      // execute query
      stmnt.executeUpdate();
      // PageStored
      String createdResult = "Created Page!";
      HttpResponse PageStored = new HttpResponse(createdResult, HttpURLConnection.HTTP_CREATED);
      return PageStored;
    } catch (Exception e) {
      e.printStackTrace();
      // InternalError
      String error = "Problems: " + e.getMessage();
      HttpResponse InternalError = new HttpResponse(error, HttpURLConnection.HTTP_INTERNAL_ERROR);
      return InternalError;
    } finally {
      // free resources
      try {
        stmnt.close();
        conn.close();
      } catch (Exception e) {
        e.printStackTrace();
        // InternalError
        String error = "Problems: " + e.getMessage();
        HttpResponse internalError = new HttpResponse(error, HttpURLConnection.HTTP_INTERNAL_ERROR);
        return internalError;
      }
    }
  }


  // //////////////////////////////////////////////////////////////////////////////////////
  // Methods required by the LAS2peer framework.
  // //////////////////////////////////////////////////////////////////////////////////////


  /**
   * 
   * This method is needed for every RESTful application in LAS2peer. Please don't change.
   * 
   * @return the mapping
   * 
   */
  public String getRESTMapping() {
    String result = "";
    try {
      result = RESTMapper.getMethodsAsXML(this.getClass());
    } catch (Exception e) {
      e.printStackTrace();
    }
    return result;
  }


  /**
   * 
   * Returns the API documentation of all annotated resources for purposes of Swagger documentation.
   * 
   * @return The resource's documentation
   * 
   */
  @GET
  @Path("/swagger.json")
  @Produces(MediaType.APPLICATION_JSON)
  public HttpResponse getSwaggerJSON() {
    Swagger swagger = new Reader(new Swagger()).read(this.getClass());
    if (swagger == null) {
      return new HttpResponse("Swagger API declaration not available!",
          HttpURLConnection.HTTP_NOT_FOUND);
    }
    try {
      return new HttpResponse(Json.mapper().writeValueAsString(swagger), HttpURLConnection.HTTP_OK);
    } catch (JsonProcessingException e) {
      e.printStackTrace();
      return new HttpResponse(e.getMessage(), HttpURLConnection.HTTP_INTERNAL_ERROR);
    }
  }

}
